version: '3.8'
services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./BE/BE-config/.env
    ports:
      - '3000:3000'
    volumes:
      - ./BE/src:/app/src
    restart: always
    networks:
      - default
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - ./BE/BE-config/.env
    ports:
      - '5432:5432'
    volumes:
      - shared-data:/var/lib/postgresql/data
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  shared-data:
