version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - '3000:3000'
    volumes:
      - ./api-gateway/src:/app/src
    restart: always
    networks:
      - default
    depends_on:
      - shared-db
    env_file:
      - ./api-gateway/api-gateway-config/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3001:3000'
    volumes:
      - ./web/src:/app/src
    restart: always
    networks:
      - default
    depends_on:
      - shared-db
    env_file:
      - ./web/web-config/.env

  shared-db:
    image: postgres:latest
    container_name: shared-db
    env_file:
      - ./api-gateway/api-gateway-config/.env
    ports:
      - '5432:5432'
    volumes:
      - shared-data:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  shared-pgadmin:
    container_name: shared-pgadmin4
    image: dpage/pgadmin4
    env_file: ./web/web-config/.env
    ports:
      - '8081:80'
    restart: always
    depends_on:
      - shared-db

networks:
  # chat-network:
  #   driver: bridge
  default:
    driver: bridge

volumes:
  shared-data:
